version: "3.8"

services:
  transfer:
    image: transfer:dev
    container_name: transfer
    hostname: transfer
    restart: always
    build: $PWD
    volumes:
      - $PWD/config.yaml:/etc/transfer/config.yaml
    ports:
      - 3000:3000
